### ISSUE TITLE
Question from customer

### ISSUE THREAD

**Issue by kennyklee** [opendns/SampleBlockPages#4]
@tresni @aharrison7 

Cisco Umbrella documentation reference this Github repo here.
https://support.umbrella.com/hc/en-us/articles/231265808-Setting-up-a-Block-Page-a-Block-Page-Bypass-User-and-a-Block-Page-Bypass-Code

**Question:**
Can I customize this block page for the company? CSS and JS?

If so, how? There doesn't seem to be a UI in Umbrella that allows that.  Am I able to write/execute `<script>lovelyCode()</script>`  in the custom message textbox in the UI?

**Comment by rgrue** [comment]
Hi @kennyklee 

These sample pages are intended for customers that want to deploy their own server to host custom block pages, as described in the "Using a Block Page Redirect Instead of a Block Page" section of the documentation you linked to. 

The custom appearance section in the Umbrella UI doesn't allow the use of scripts due to security concerns.

Let us know if you have any more questions!

**Comment by iseptimus** [comment]
Is there a way to pass the URL, and IP into the message produced this example?

Thanks.
